import Currency from "../models/Currency";
import { CurrencyCode } from "../models/CurrencyCode";

const currenciesMap: Record<CurrencyCode, Currency> = {
	[CurrencyCode.USD]: {
		code: CurrencyCode.USD,
		name: "US Dollar",
		symbol: "$",
		rateToUSD: 1,
		decimals: 2,
		country: "USA",
		flag: "🇺🇸",
	},
	[CurrencyCode.EUR]: {
		code: CurrencyCode.EUR,
		name: "Euro",
		symbol: "€",
		rateToUSD: 1.08,
		decimals: 2,
		country: "EU",
		flag: "🇪🇺",
	},
	[CurrencyCode.PLN]: {
		code: CurrencyCode.PLN,
		name: "Polish Złoty",
		symbol: "zł",
		rateToUSD: 0.22,
		decimals: 2,
		country: "Poland",
		flag: "🇵🇱",
	},
	[CurrencyCode.GBP]: {
		code: CurrencyCode.GBP,
		name: "British Pound",
		symbol: "£",
		rateToUSD: 1.25,
		decimals: 2,
		country: "UK",
		flag: "🇬🇧",
	},
	[CurrencyCode.JPY]: {
		code: CurrencyCode.JPY,
		name: "Japanese Yen",
		symbol: "¥",
		rateToUSD: 0.0073,
		decimals: 0,
		country: "Japan",
		flag: "🇯🇵",
	},
	[CurrencyCode.AUD]: {
		code: CurrencyCode.AUD,
		name: "Australian Dollar",
		symbol: "A$",
		rateToUSD: 0.67,
		decimals: 2,
		country: "Australia",
		flag: "🇦🇺",
	},
	[CurrencyCode.CAD]: {
		code: CurrencyCode.CAD,
		name: "Canadian Dollar",
		symbol: "C$",
		rateToUSD: 0.73,
		decimals: 2,
		country: "Canada",
		flag: "🇨🇦",
	},
	[CurrencyCode.CHF]: {
		code: CurrencyCode.CHF,
		name: "Swiss Franc",
		symbol: "CHF",
		rateToUSD: 1.11,
		decimals: 2,
		country: "Switzerland",
		flag: "🇨🇭",
	},
	[CurrencyCode.CNY]: {
		code: CurrencyCode.CNY,
		name: "Chinese Yuan",
		symbol: "¥",
		rateToUSD: 0.14,
		decimals: 2,
		country: "China",
		flag: "🇨🇳",
	},
	[CurrencyCode.SEK]: {
		code: CurrencyCode.SEK,
		name: "Swedish Krona",
		symbol: "kr",
		rateToUSD: 0.092,
		decimals: 2,
		country: "Sweden",
		flag: "🇸🇪",
	},
	[CurrencyCode.NZD]: {
		code: CurrencyCode.NZD,
		name: "New Zealand Dollar",
		symbol: "NZ$",
		rateToUSD: 0.6,
		decimals: 2,
		country: "New Zealand",
		flag: "🇳🇿",
	},
	[CurrencyCode.SGD]: {
		code: CurrencyCode.SGD,
		name: "Singapore Dollar",
		symbol: "S$",
		rateToUSD: 0.74,
		decimals: 2,
		country: "Singapore",
		flag: "🇸🇬",
	},
	[CurrencyCode.HKD]: {
		code: CurrencyCode.HKD,
		name: "Hong Kong Dollar",
		symbol: "HK$",
		rateToUSD: 0.13,
		decimals: 2,
		country: "Hong Kong",
		flag: "🇭🇰",
	},
	[CurrencyCode.NOK]: {
		code: CurrencyCode.NOK,
		name: "Norwegian Krone",
		symbol: "kr",
		rateToUSD: 0.089,
		decimals: 2,
		country: "Norway",
		flag: "🇳🇴",
	},
	[CurrencyCode.KRW]: {
		code: CurrencyCode.KRW,
		name: "South Korean Won",
		symbol: "₩",
		rateToUSD: 0.00076,
		decimals: 0,
		country: "South Korea",
		flag: "🇰🇷",
	},
	[CurrencyCode.MXN]: {
		code: CurrencyCode.MXN,
		name: "Mexican Peso",
		symbol: "$",
		rateToUSD: 0.054,
		decimals: 2,
		country: "Mexico",
		flag: "🇲🇽",
	},
	[CurrencyCode.INR]: {
		code: CurrencyCode.INR,
		name: "Indian Rupee",
		symbol: "₹",
		rateToUSD: 0.012,
		decimals: 2,
		country: "India",
		flag: "🇮🇳",
	},
	[CurrencyCode.BRL]: {
		code: CurrencyCode.BRL,
		name: "Brazilian Real",
		symbol: "R$",
		rateToUSD: 0.19,
		decimals: 2,
		country: "Brazil",
		flag: "🇧🇷",
	},
	[CurrencyCode.RUB]: {
		code: CurrencyCode.RUB,
		name: "Russian Ruble",
		symbol: "₽",
		rateToUSD: 0.013,
		decimals: 2,
		country: "Russia",
		flag: "🇷🇺",
	},
	[CurrencyCode.ZAR]: {
		code: CurrencyCode.ZAR,
		name: "South African Rand",
		symbol: "R",
		rateToUSD: 0.055,
		decimals: 2,
		country: "South Africa",
		flag: "🇿🇦",
	},
	[CurrencyCode.THB]: {
		code: CurrencyCode.THB,
		name: "Thai Baht",
		symbol: "฿",
		rateToUSD: 0.027,
		decimals: 2,
		country: "Thailand",
		flag: "🇹🇭",
	},
	[CurrencyCode.MYR]: {
		code: CurrencyCode.MYR,
		name: "Malaysian Ringgit",
		symbol: "RM",
		rateToUSD: 0.22,
		decimals: 2,
		country: "Malaysia",
		flag: "🇲🇾",
	},
	[CurrencyCode.IDR]: {
		code: CurrencyCode.IDR,
		name: "Indonesian Rupiah",
		symbol: "Rp",
		rateToUSD: 0.000066,
		decimals: 0,
		country: "Indonesia",
		flag: "🇮🇩",
	},
	[CurrencyCode.PHP]: {
		code: CurrencyCode.PHP,
		name: "Philippine Peso",
		symbol: "₱",
		rateToUSD: 0.018,
		decimals: 2,
		country: "Philippines",
		flag: "🇵🇭",
	},
	[CurrencyCode.CZK]: {
		code: CurrencyCode.CZK,
		name: "Czech Koruna",
		symbol: "Kč",
		rateToUSD: 0.044,
		decimals: 2,
		country: "Czechia",
		flag: "🇨🇿",
	},
	[CurrencyCode.HUF]: {
		code: CurrencyCode.HUF,
		name: "Hungarian Forint",
		symbol: "Ft",
		rateToUSD: 0.0027,
		decimals: 0,
		country: "Hungary",
		flag: "🇭🇺",
	},
	[CurrencyCode.DKK]: {
		code: CurrencyCode.DKK,
		name: "Danish Krone",
		symbol: "kr",
		rateToUSD: 0.14,
		decimals: 2,
		country: "Denmark",
		flag: "🇩🇰",
	},
	[CurrencyCode.ILS]: {
		code: CurrencyCode.ILS,
		name: "Israeli New Shekel",
		symbol: "₪",
		rateToUSD: 0.27,
		decimals: 2,
		country: "Israel",
		flag: "🇮🇱",
	},
	[CurrencyCode.SAR]: {
		code: CurrencyCode.SAR,
		name: "Saudi Riyal",
		symbol: "﷼",
		rateToUSD: 0.27,
		decimals: 2,
		country: "Saudi Arabia",
		flag: "🇸🇦",
	},
	[CurrencyCode.AED]: {
		code: CurrencyCode.AED,
		name: "UAE Dirham",
		symbol: "د.إ",
		rateToUSD: 0.27,
		decimals: 2,
		country: "UAE",
		flag: "🇦🇪",
	},
	[CurrencyCode.KWD]: {
		code: CurrencyCode.KWD,
		name: "Kuwaiti Dinar",
		symbol: "د.ك",
		rateToUSD: 3.25,
		decimals: 3,
		country: "Kuwait",
		flag: "🇰🇼",
	},
	[CurrencyCode.QAR]: {
		code: CurrencyCode.QAR,
		name: "Qatari Riyal",
		symbol: "﷼",
		rateToUSD: 0.27,
		decimals: 2,
		country: "Qatar",
		flag: "🇶🇦",
	},
	[CurrencyCode.NZD]: {
		code: CurrencyCode.NZD,
		name: "New Zealand Dollar",
		symbol: "NZ$",
		rateToUSD: 0.6,
		decimals: 2,
		country: "New Zealand",
		flag: "🇳🇿",
	},
	[CurrencyCode.AUD]: {
		code: CurrencyCode.AUD,
		name: "Australian Dollar",
		symbol: "A$",
		rateToUSD: 0.67,
		decimals: 2,
		country: "Australia",
		flag: "🇦🇺",
	},
	[CurrencyCode.CAD]: {
		code: CurrencyCode.CAD,
		name: "Canadian Dollar",
		symbol: "C$",
		rateToUSD: 0.73,
		decimals: 2,
		country: "Canada",
		flag: "🇨🇦",
	},
	[CurrencyCode.CNY]: {
		code: CurrencyCode.CNY,
		name: "Chinese Yuan",
		symbol: "¥",
		rateToUSD: 0.14,
		decimals: 2,
		country: "China",
		flag: "🇨🇳",
	},
	[CurrencyCode.AFN]: {
		code: CurrencyCode.AFN,
		name: "Afghan Afghani",
		symbol: "؋",
		rateToUSD: 0,
		decimals: 2,
		country: "Afghanistan",
		flag: "🇦🇫",
	},
	[CurrencyCode.ALL]: {
		code: CurrencyCode.ALL,
		name: "Albanian Lek",
		symbol: "L",
		rateToUSD: 0,
		decimals: 2,
		country: "Albania",
		flag: "🇦🇱",
	},
	[CurrencyCode.AMD]: {
		code: CurrencyCode.AMD,
		name: "Armenian Dram",
		symbol: "֏",
		rateToUSD: 0,
		decimals: 2,
		country: "Armenia",
		flag: "🇦🇲",
	},
	[CurrencyCode.ANG]: {
		code: CurrencyCode.ANG,
		name: "Netherlands Antillean Guilder",
		symbol: "ƒ",
		rateToUSD: 0,
		decimals: 2,
		country: "Curacao",
		flag: "🇨🇼",
	},
	[CurrencyCode.AOA]: {
		code: CurrencyCode.AOA,
		name: "Angolan Kwanza",
		symbol: "Kz",
		rateToUSD: 0,
		decimals: 2,
		country: "Angola",
		flag: "🇦🇴",
	},
	[CurrencyCode.ARS]: {
		code: CurrencyCode.ARS,
		name: "Argentine Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Argentina",
		flag: "🇦🇷",
	},
	[CurrencyCode.AUD]: {
		code: CurrencyCode.AUD,
		name: "Australian Dollar",
		symbol: "A$",
		rateToUSD: 0,
		decimals: 2,
		country: "Australia",
		flag: "🇦🇺",
	},
	[CurrencyCode.AWG]: {
		code: CurrencyCode.AWG,
		name: "Aruban Florin",
		symbol: "ƒ",
		rateToUSD: 0,
		decimals: 2,
		country: "Aruba",
		flag: "🇦🇼",
	},
	[CurrencyCode.AZN]: {
		code: CurrencyCode.AZN,
		name: "Azerbaijani Manat",
		symbol: "₼",
		rateToUSD: 0,
		decimals: 2,
		country: "Azerbaijan",
		flag: "🇦🇿",
	},
	[CurrencyCode.BAM]: {
		code: CurrencyCode.BAM,
		name: "Bosnian Convertible Mark",
		symbol: "KM",
		rateToUSD: 0,
		decimals: 2,
		country: "Bosnia and Herzegovina",
		flag: "🇧🇦",
	},
	[CurrencyCode.BBD]: {
		code: CurrencyCode.BBD,
		name: "Barbadian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Barbados",
		flag: "🇧🇧",
	},
	[CurrencyCode.BDT]: {
		code: CurrencyCode.BDT,
		name: "Bangladeshi Taka",
		symbol: "৳",
		rateToUSD: 0,
		decimals: 2,
		country: "Bangladesh",
		flag: "🇧🇩",
	},
	[CurrencyCode.BGN]: {
		code: CurrencyCode.BGN,
		name: "Bulgarian Lev",
		symbol: "лв",
		rateToUSD: 0,
		decimals: 2,
		country: "Bulgaria",
		flag: "🇧🇬",
	},
	[CurrencyCode.BHD]: {
		code: CurrencyCode.BHD,
		name: "Bahraini Dinar",
		symbol: ".د.ب",
		rateToUSD: 0,
		decimals: 3,
		country: "Bahrain",
		flag: "🇧🇭",
	},
	[CurrencyCode.BIF]: {
		code: CurrencyCode.BIF,
		name: "Burundian Franc",
		symbol: "FBu",
		rateToUSD: 0,
		decimals: 0,
		country: "Burundi",
		flag: "🇧🇮",
	},
	[CurrencyCode.BMD]: {
		code: CurrencyCode.BMD,
		name: "Bermudian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Bermuda",
		flag: "🇧🇲",
	},
	[CurrencyCode.BND]: {
		code: CurrencyCode.BND,
		name: "Brunei Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Brunei",
		flag: "🇧🇳",
	},
	[CurrencyCode.BOB]: {
		code: CurrencyCode.BOB,
		name: "Bolivian Boliviano",
		symbol: "Bs",
		rateToUSD: 0,
		decimals: 2,
		country: "Bolivia",
		flag: "🇧🇴",
	},
	[CurrencyCode.BOV]: {
		code: CurrencyCode.BOV,
		name: "Bolivian Mvdol",
		symbol: "BOV",
		rateToUSD: 0,
		decimals: 2,
		country: "Bolivia",
		flag: "🇧🇴",
	},
	[CurrencyCode.BSD]: {
		code: CurrencyCode.BSD,
		name: "Bahamian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Bahamas",
		flag: "🇧🇸",
	},
	[CurrencyCode.BTN]: {
		code: CurrencyCode.BTN,
		name: "Bhutanese Ngultrum",
		symbol: "Nu.",
		rateToUSD: 0,
		decimals: 2,
		country: "Bhutan",
		flag: "🇧🇹",
	},
	[CurrencyCode.BWP]: {
		code: CurrencyCode.BWP,
		name: "Botswanan Pula",
		symbol: "P",
		rateToUSD: 0,
		decimals: 2,
		country: "Botswana",
		flag: "🇧🇼",
	},
	[CurrencyCode.BYN]: {
		code: CurrencyCode.BYN,
		name: "Belarusian Ruble",
		symbol: "Br",
		rateToUSD: 0,
		decimals: 2,
		country: "Belarus",
		flag: "🇧🇾",
	},
	[CurrencyCode.BZD]: {
		code: CurrencyCode.BZD,
		name: "Belize Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Belize",
		flag: "🇧🇿",
	},
	[CurrencyCode.CDF]: {
		code: CurrencyCode.CDF,
		name: "Congolese Franc",
		symbol: "FC",
		rateToUSD: 0,
		decimals: 2,
		country: "DR Congo",
		flag: "🇨🇩",
	},
	[CurrencyCode.CHE]: {
		code: CurrencyCode.CHE,
		name: "WIR Euro",
		symbol: "CHE",
		rateToUSD: 0,
		decimals: 2,
		country: "Switzerland",
		flag: "🇨🇭",
	},
	[CurrencyCode.CHW]: {
		code: CurrencyCode.CHW,
		name: "WIR Franc",
		symbol: "CHW",
		rateToUSD: 0,
		decimals: 2,
		country: "Switzerland",
		flag: "🇨🇭",
	},
	[CurrencyCode.CLP]: {
		code: CurrencyCode.CLP,
		name: "Chilean Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 0,
		country: "Chile",
		flag: "🇨🇱",
	},
	[CurrencyCode.COP]: {
		code: CurrencyCode.COP,
		name: "Colombian Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Colombia",
		flag: "🇨🇴",
	},
	[CurrencyCode.CRC]: {
		code: CurrencyCode.CRC,
		name: "Costa Rican Colón",
		symbol: "₡",
		rateToUSD: 0,
		decimals: 2,
		country: "Costa Rica",
		flag: "🇨🇷",
	},
	[CurrencyCode.CUP]: {
		code: CurrencyCode.CUP,
		name: "Cuban Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Cuba",
		flag: "🇨🇺",
	},
	[CurrencyCode.CVE]: {
		code: CurrencyCode.CVE,
		name: "Cape Verdean Escudo",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Cabo Verde",
		flag: "🇨🇻",
	},
	[CurrencyCode.DJF]: {
		code: CurrencyCode.DJF,
		name: "Djiboutian Franc",
		symbol: "Fdj",
		rateToUSD: 0,
		decimals: 2,
		country: "Djibouti",
		flag: "🇩🇯",
	},
	[CurrencyCode.DOP]: {
		code: CurrencyCode.DOP,
		name: "Dominican Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Dominican Republic",
		flag: "🇩🇴",
	},
	[CurrencyCode.DZD]: {
		code: CurrencyCode.DZD,
		name: "Algerian Dinar",
		symbol: "دج",
		rateToUSD: 0,
		decimals: 2,
		country: "Algeria",
		flag: "🇩🇿",
	},
	[CurrencyCode.EGP]: {
		code: CurrencyCode.EGP,
		name: "Egyptian Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "Egypt",
		flag: "🇪🇬",
	},
	[CurrencyCode.ERN]: {
		code: CurrencyCode.ERN,
		name: "Eritrean Nakfa",
		symbol: "Nfk",
		rateToUSD: 0,
		decimals: 2,
		country: "Eritrea",
		flag: "🇪🇷",
	},
	[CurrencyCode.ETB]: {
		code: CurrencyCode.ETB,
		name: "Ethiopian Birr",
		symbol: "Br",
		rateToUSD: 0,
		decimals: 2,
		country: "Ethiopia",
		flag: "🇪🇹",
	},
	[CurrencyCode.FJD]: {
		code: CurrencyCode.FJD,
		name: "Fijian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Fiji",
		flag: "🇫🇯",
	},
	[CurrencyCode.FKP]: {
		code: CurrencyCode.FKP,
		name: "Falkland Islands Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "Falkland Islands",
		flag: "🇫🇰",
	},
	[CurrencyCode.GEL]: {
		code: CurrencyCode.GEL,
		name: "Georgian Lari",
		symbol: "₾",
		rateToUSD: 0,
		decimals: 2,
		country: "Georgia",
		flag: "🇬🇪",
	},
	[CurrencyCode.GGP]: {
		code: CurrencyCode.GGP,
		name: "Guernsey Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "Guernsey",
		flag: "🇬🇬",
	},
	[CurrencyCode.GHS]: {
		code: CurrencyCode.GHS,
		name: "Ghanaian Cedi",
		symbol: "₵",
		rateToUSD: 0,
		decimals: 2,
		country: "Ghana",
		flag: "🇬🇭",
	},
	[CurrencyCode.GIP]: {
		code: CurrencyCode.GIP,
		name: "Gibraltar Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "Gibraltar",
		flag: "🇬🇮",
	},
	[CurrencyCode.GMD]: {
		code: CurrencyCode.GMD,
		name: "Gambian Dalasi",
		symbol: "D",
		rateToUSD: 0,
		decimals: 2,
		country: "Gambia",
		flag: "🇬🇲",
	},
	[CurrencyCode.GNF]: {
		code: CurrencyCode.GNF,
		name: "Guinean Franc",
		symbol: "FG",
		rateToUSD: 0,
		decimals: 2,
		country: "Guinea",
		flag: "🇬🇳",
	},
	[CurrencyCode.GYD]: {
		code: CurrencyCode.GYD,
		name: "Guyanaese Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Guyana",
		flag: "🇬🇾",
	},
	[CurrencyCode.HNL]: {
		code: CurrencyCode.HNL,
		name: "Honduran Lempira",
		symbol: "L",
		rateToUSD: 0,
		decimals: 2,
		country: "Honduras",
		flag: "🇭🇳",
	},
	[CurrencyCode.HRK]: {
		code: CurrencyCode.HRK,
		name: "Croatian Kuna",
		symbol: "kn",
		rateToUSD: 0,
		decimals: 2,
		country: "Croatia",
		flag: "🇭🇷",
	},
	[CurrencyCode.HTG]: {
		code: CurrencyCode.HTG,
		name: "Haitian Gourde",
		symbol: "G",
		rateToUSD: 0,
		decimals: 2,
		country: "Haiti",
		flag: "🇭🇹",
	},
	[CurrencyCode.IQD]: {
		code: CurrencyCode.IQD,
		name: "Iraqi Dinar",
		symbol: "ع.د",
		rateToUSD: 0,
		decimals: 3,
		country: "Iraq",
		flag: "🇮🇶",
	},
	[CurrencyCode.IRR]: {
		code: CurrencyCode.IRR,
		name: "Iranian Rial",
		symbol: "﷼",
		rateToUSD: 0,
		decimals: 0,
		country: "Iran",
		flag: "🇮🇷",
	},
	[CurrencyCode.ISK]: {
		code: CurrencyCode.ISK,
		name: "Icelandic Króna",
		symbol: "kr",
		rateToUSD: 0,
		decimals: 0,
		country: "Iceland",
		flag: "🇮🇸",
	},
	[CurrencyCode.JMD]: {
		code: CurrencyCode.JMD,
		name: "Jamaican Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Jamaica",
		flag: "🇯🇲",
	},
	[CurrencyCode.JOD]: {
		code: CurrencyCode.JOD,
		name: "Jordanian Dinar",
		symbol: "د.ا",
		rateToUSD: 0,
		decimals: 3,
		country: "Jordan",
		flag: "🇯🇴",
	},
	[CurrencyCode.KES]: {
		code: CurrencyCode.KES,
		name: "Kenyan Shilling",
		symbol: "Sh",
		rateToUSD: 0,
		decimals: 2,
		country: "Kenya",
		flag: "🇰🇪",
	},
	[CurrencyCode.KGS]: {
		code: CurrencyCode.KGS,
		name: "Kyrgyzstani Som",
		symbol: "лв",
		rateToUSD: 0,
		decimals: 2,
		country: "Kyrgyzstan",
		flag: "🇰🇬",
	},
	[CurrencyCode.KHR]: {
		code: CurrencyCode.KHR,
		name: "Cambodian Riel",
		symbol: "៛",
		rateToUSD: 0,
		decimals: 2,
		country: "Cambodia",
		flag: "🇰🇭",
	},
	[CurrencyCode.KMF]: {
		code: CurrencyCode.KMF,
		name: "Comorian Franc",
		symbol: "CF",
		rateToUSD: 0,
		decimals: 0,
		country: "Comoros",
		flag: "🇰🇲",
	},
	[CurrencyCode.KPW]: {
		code: CurrencyCode.KPW,
		name: "North Korean Won",
		symbol: "₩",
		rateToUSD: 0,
		decimals: 0,
		country: "North Korea",
		flag: "🇰🇵",
	},
	[CurrencyCode.KYD]: {
		code: CurrencyCode.KYD,
		name: "Cayman Islands Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Cayman Islands",
		flag: "🇰🇾",
	},
	[CurrencyCode.KZT]: {
		code: CurrencyCode.KZT,
		name: "Kazakhstani Tenge",
		symbol: "₸",
		rateToUSD: 0,
		decimals: 2,
		country: "Kazakhstan",
		flag: "🇰🇿",
	},
	[CurrencyCode.LAK]: {
		code: CurrencyCode.LAK,
		name: "Lao Kip",
		symbol: "₭",
		rateToUSD: 0,
		decimals: 2,
		country: "Laos",
		flag: "🇱🇦",
	},
	[CurrencyCode.LBP]: {
		code: CurrencyCode.LBP,
		name: "Lebanese Pound",
		symbol: "ل.ل",
		rateToUSD: 0,
		decimals: 0,
		country: "Lebanon",
		flag: "🇱🇧",
	},
	[CurrencyCode.LKR]: {
		code: CurrencyCode.LKR,
		name: "Sri Lankan Rupee",
		symbol: "Rs",
		rateToUSD: 0,
		decimals: 2,
		country: "Sri Lanka",
		flag: "🇱🇰",
	},
	[CurrencyCode.LRD]: {
		code: CurrencyCode.LRD,
		name: "Liberian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Liberia",
		flag: "🇱🇷",
	},
	[CurrencyCode.LSL]: {
		code: CurrencyCode.LSL,
		name: "Lesotho Loti",
		symbol: "L",
		rateToUSD: 0,
		decimals: 2,
		country: "Lesotho",
		flag: "🇱🇸",
	},
	[CurrencyCode.LTL]: {
		code: CurrencyCode.LTL,
		name: "Lithuanian Litas",
		symbol: "Lt",
		rateToUSD: 0,
		decimals: 2,
		country: "Lithuania",
		flag: "🇱🇹",
	},
	[CurrencyCode.LVL]: {
		code: CurrencyCode.LVL,
		name: "Latvian Lats",
		symbol: "Ls",
		rateToUSD: 0,
		decimals: 2,
		country: "Latvia",
		flag: "🇱🇻",
	},
	[CurrencyCode.LYD]: {
		code: CurrencyCode.LYD,
		name: "Libyan Dinar",
		symbol: "ل.د",
		rateToUSD: 0,
		decimals: 3,
		country: "Libya",
		flag: "🇱🇾",
	},
	[CurrencyCode.MAD]: {
		code: CurrencyCode.MAD,
		name: "Moroccan Dirham",
		symbol: "DH",
		rateToUSD: 0,
		decimals: 2,
		country: "Morocco",
		flag: "🇲🇦",
	},
	[CurrencyCode.MDL]: {
		code: CurrencyCode.MDL,
		name: "Moldovan Leu",
		symbol: "L",
		rateToUSD: 0,
		decimals: 2,
		country: "Moldova",
		flag: "🇲🇩",
	},
	[CurrencyCode.MGA]: {
		code: CurrencyCode.MGA,
		name: "Malagasy Ariary",
		symbol: "Ar",
		rateToUSD: 0,
		decimals: 2,
		country: "Madagascar",
		flag: "🇲🇬",
	},
	[CurrencyCode.MKD]: {
		code: CurrencyCode.MKD,
		name: "Macedonian Denar",
		symbol: "ден",
		rateToUSD: 0,
		decimals: 2,
		country: "North Macedonia",
		flag: "🇲🇰",
	},
	[CurrencyCode.MMK]: {
		code: CurrencyCode.MMK,
		name: "Burmese Kyat",
		symbol: "Ks",
		rateToUSD: 0,
		decimals: 2,
		country: "Myanmar",
		flag: "🇲🇲",
	},
	[CurrencyCode.MNT]: {
		code: CurrencyCode.MNT,
		name: "Mongolian Tögrög",
		symbol: "₮",
		rateToUSD: 0,
		decimals: 2,
		country: "Mongolia",
		flag: "🇲🇳",
	},
	[CurrencyCode.MOP]: {
		code: CurrencyCode.MOP,
		name: "Macanese Pataca",
		symbol: "P",
		rateToUSD: 0,
		decimals: 2,
		country: "Macau",
		flag: "🇲🇴",
	},
	[CurrencyCode.MRU]: {
		code: CurrencyCode.MRU,
		name: "Mauritanian Ouguiya",
		symbol: "UM",
		rateToUSD: 0,
		decimals: 2,
		country: "Mauritania",
		flag: "🇲🇷",
	},
	[CurrencyCode.MUR]: {
		code: CurrencyCode.MUR,
		name: "Mauritian Rupee",
		symbol: "Rs",
		rateToUSD: 0,
		decimals: 2,
		country: "Mauritius",
		flag: "🇲🇺",
	},
	[CurrencyCode.MVR]: {
		code: CurrencyCode.MVR,
		name: "Maldivian Rufiyaa",
		symbol: "Rf",
		rateToUSD: 0,
		decimals: 2,
		country: "Maldives",
		flag: "🇲🇻",
	},
	[CurrencyCode.MWK]: {
		code: CurrencyCode.MWK,
		name: "Malawian Kwacha",
		symbol: "MK",
		rateToUSD: 0,
		decimals: 2,
		country: "Malawi",
		flag: "🇲🇼",
	},
	[CurrencyCode.MZN]: {
		code: CurrencyCode.MZN,
		name: "Mozambican Metical",
		symbol: "MT",
		rateToUSD: 0,
		decimals: 2,
		country: "Mozambique",
		flag: "🇲🇿",
	},
	[CurrencyCode.NAD]: {
		code: CurrencyCode.NAD,
		name: "Namibian Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Namibia",
		flag: "🇳🇦",
	},
	[CurrencyCode.NGN]: {
		code: CurrencyCode.NGN,
		name: "Nigerian Naira",
		symbol: "₦",
		rateToUSD: 0,
		decimals: 2,
		country: "Nigeria",
		flag: "🇳🇬",
	},
	[CurrencyCode.NIO]: {
		code: CurrencyCode.NIO,
		name: "Nicaraguan Córdoba",
		symbol: "C$",
		rateToUSD: 0,
		decimals: 2,
		country: "Nicaragua",
		flag: "🇳🇮",
	},
	[CurrencyCode.NPR]: {
		code: CurrencyCode.NPR,
		name: "Nepalese Rupee",
		symbol: "Rs",
		rateToUSD: 0,
		decimals: 2,
		country: "Nepal",
		flag: "🇳🇵",
	},
	[CurrencyCode.OMR]: {
		code: CurrencyCode.OMR,
		name: "Omani Rial",
		symbol: "ر.ع.",
		rateToUSD: 0,
		decimals: 3,
		country: "Oman",
		flag: "🇴🇲",
	},
	[CurrencyCode.PAB]: {
		code: CurrencyCode.PAB,
		name: "Panamanian Balboa",
		symbol: "B/.",
		rateToUSD: 0,
		decimals: 2,
		country: "Panama",
		flag: "🇵🇦",
	},
	[CurrencyCode.PEN]: {
		code: CurrencyCode.PEN,
		name: "Peruvian Sol",
		symbol: "S/",
		rateToUSD: 0,
		decimals: 2,
		country: "Peru",
		flag: "🇵🇪",
	},
	[CurrencyCode.PGK]: {
		code: CurrencyCode.PGK,
		name: "Papua New Guinean Kina",
		symbol: "K",
		rateToUSD: 0,
		decimals: 2,
		country: "Papua New Guinea",
		flag: "🇵🇬",
	},
	[CurrencyCode.PKR]: {
		code: CurrencyCode.PKR,
		name: "Pakistani Rupee",
		symbol: "Rs",
		rateToUSD: 0,
		decimals: 2,
		country: "Pakistan",
		flag: "🇵🇰",
	},
	[CurrencyCode.PYG]: {
		code: CurrencyCode.PYG,
		name: "Paraguayan Guaraní",
		symbol: "₲",
		rateToUSD: 0,
		decimals: 0,
		country: "Paraguay",
		flag: "🇵🇾",
	},
	[CurrencyCode.RON]: {
		code: CurrencyCode.RON,
		name: "Romanian Leu",
		symbol: "lei",
		rateToUSD: 0,
		decimals: 2,
		country: "Romania",
		flag: "🇷🇴",
	},
	[CurrencyCode.RSD]: {
		code: CurrencyCode.RSD,
		name: "Serbian Dinar",
		symbol: "дин.",
		rateToUSD: 0,
		decimals: 2,
		country: "Serbia",
		flag: "🇷🇸",
	},
	[CurrencyCode.RWF]: {
		code: CurrencyCode.RWF,
		name: "Rwandan Franc",
		symbol: "RF",
		rateToUSD: 0,
		decimals: 0,
		country: "Rwanda",
		flag: "🇷🇼",
	},
	[CurrencyCode.SBD]: {
		code: CurrencyCode.SBD,
		name: "Solomon Islands Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Solomon Islands",
		flag: "🇸🇧",
	},
	[CurrencyCode.SCR]: {
		code: CurrencyCode.SCR,
		name: "Seychellois Rupee",
		symbol: "Rs",
		rateToUSD: 0,
		decimals: 2,
		country: "Seychelles",
		flag: "🇸🇨",
	},
	[CurrencyCode.SDG]: {
		code: CurrencyCode.SDG,
		name: "Sudanese Pound",
		symbol: "ج.س.",
		rateToUSD: 0,
		decimals: 2,
		country: "Sudan",
		flag: "🇸🇩",
	},
	[CurrencyCode.SHP]: {
		code: CurrencyCode.SHP,
		name: "Saint Helena Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "Saint Helena",
		flag: "🇸🇭",
	},
	[CurrencyCode.SLL]: {
		code: CurrencyCode.SLL,
		name: "Sierra Leonean Leone",
		symbol: "Le",
		rateToUSD: 0,
		decimals: 2,
		country: "Sierra Leone",
		flag: "🇸🇱",
	},
	[CurrencyCode.SOS]: {
		code: CurrencyCode.SOS,
		name: "Somali Shilling",
		symbol: "Sh",
		rateToUSD: 0,
		decimals: 2,
		country: "Somalia",
		flag: "🇸🇴",
	},
	[CurrencyCode.SRD]: {
		code: CurrencyCode.SRD,
		name: "Surinamese Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Suriname",
		flag: "🇸🇷",
	},
	[CurrencyCode.SSP]: {
		code: CurrencyCode.SSP,
		name: "South Sudanese Pound",
		symbol: "£",
		rateToUSD: 0,
		decimals: 2,
		country: "South Sudan",
		flag: "🇸🇸",
	},
	[CurrencyCode.STN]: {
		code: CurrencyCode.STN,
		name: "São Tomé and Príncipe Dobra",
		symbol: "Db",
		rateToUSD: 0,
		decimals: 2,
		country: "São Tomé and Príncipe",
		flag: "🇸🇹",
	},
	[CurrencyCode.SVC]: {
		code: CurrencyCode.SVC,
		name: "Salvadoran Colón",
		symbol: "₡",
		rateToUSD: 0,
		decimals: 2,
		country: "El Salvador",
		flag: "🇸🇻",
	},
	[CurrencyCode.SYP]: {
		code: CurrencyCode.SYP,
		name: "Syrian Pound",
		symbol: "£S",
		rateToUSD: 0,
		decimals: 2,
		country: "Syria",
		flag: "🇸🇾",
	},
	[CurrencyCode.SZL]: {
		code: CurrencyCode.SZL,
		name: "Swazi Lilangeni",
		symbol: "E",
		rateToUSD: 0,
		decimals: 2,
		country: "Eswatini",
		flag: "🇸🇿",
	},
	[CurrencyCode.TJS]: {
		code: CurrencyCode.TJS,
		name: "Tajikistani Somoni",
		symbol: "SM",
		rateToUSD: 0,
		decimals: 2,
		country: "Tajikistan",
		flag: "🇹🇯",
	},
	[CurrencyCode.TMT]: {
		code: CurrencyCode.TMT,
		name: "Turkmenistani Manat",
		symbol: "m",
		rateToUSD: 0,
		decimals: 2,
		country: "Turkmenistan",
		flag: "🇹🇲",
	},
	[CurrencyCode.TND]: {
		code: CurrencyCode.TND,
		name: "Tunisian Dinar",
		symbol: "د.ت",
		rateToUSD: 0,
		decimals: 3,
		country: "Tunisia",
		flag: "🇹🇳",
	},
	[CurrencyCode.TOP]: {
		code: CurrencyCode.TOP,
		name: "Tongan Paʻanga",
		symbol: "T$",
		rateToUSD: 0,
		decimals: 2,
		country: "Tonga",
		flag: "🇹🇴",
	},
	[CurrencyCode.TRY]: {
		code: CurrencyCode.TRY,
		name: "Turkish Lira",
		symbol: "₺",
		rateToUSD: 0,
		decimals: 2,
		country: "Turkey",
		flag: "🇹🇷",
	},
	[CurrencyCode.TTD]: {
		code: CurrencyCode.TTD,
		name: "Trinidad and Tobago Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Trinidad and Tobago",
		flag: "🇹🇹",
	},
	[CurrencyCode.TWD]: {
		code: CurrencyCode.TWD,
		name: "New Taiwan Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Taiwan",
		flag: "🇹🇼",
	},
	[CurrencyCode.TZS]: {
		code: CurrencyCode.TZS,
		name: "Tanzanian Shilling",
		symbol: "Sh",
		rateToUSD: 0,
		decimals: 2,
		country: "Tanzania",
		flag: "🇹🇿",
	},
	[CurrencyCode.UAH]: {
		code: CurrencyCode.UAH,
		name: "Ukrainian Hryvnia",
		symbol: "₴",
		rateToUSD: 0,
		decimals: 2,
		country: "Ukraine",
		flag: "🇺🇦",
	},
	[CurrencyCode.UGX]: {
		code: CurrencyCode.UGX,
		name: "Ugandan Shilling",
		symbol: "Sh",
		rateToUSD: 0,
		decimals: 0,
		country: "Uganda",
		flag: "🇺🇬",
	},
	[CurrencyCode.UYU]: {
		code: CurrencyCode.UYU,
		name: "Uruguayan Peso",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Uruguay",
		flag: "🇺🇾",
	},
	[CurrencyCode.UZS]: {
		code: CurrencyCode.UZS,
		name: "Uzbekistani Som",
		symbol: "so'm",
		rateToUSD: 0,
		decimals: 2,
		country: "Uzbekistan",
		flag: "🇺🇿",
	},
	[CurrencyCode.VEF]: {
		code: CurrencyCode.VEF,
		name: "Venezuelan Bolívar",
		symbol: "Bs",
		rateToUSD: 0,
		decimals: 2,
		country: "Venezuela",
		flag: "🇻🇪",
	},
	[CurrencyCode.VND]: {
		code: CurrencyCode.VND,
		name: "Vietnamese Dong",
		symbol: "₫",
		rateToUSD: 0,
		decimals: 0,
		country: "Vietnam",
		flag: "🇻🇳",
	},
	[CurrencyCode.VUV]: {
		code: CurrencyCode.VUV,
		name: "Vanuatu Vatu",
		symbol: "Vt",
		rateToUSD: 0,
		decimals: 0,
		country: "Vanuatu",
		flag: "🇻🇺",
	},
	[CurrencyCode.WST]: {
		code: CurrencyCode.WST,
		name: "Samoan Tala",
		symbol: "T",
		rateToUSD: 0,
		decimals: 2,
		country: "Samoa",
		flag: "🇼🇸",
	},
	[CurrencyCode.XAF]: {
		code: CurrencyCode.XAF,
		name: "CFA Franc BEAC",
		symbol: "Fr",
		rateToUSD: 0,
		decimals: 0,
		country: "Central African CFA",
		flag: "🇨🇫",
	},
	[CurrencyCode.XCD]: {
		code: CurrencyCode.XCD,
		name: "East Caribbean Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "East Caribbean",
		flag: "🇦🇮",
	},
	[CurrencyCode.XOF]: {
		code: CurrencyCode.XOF,
		name: "CFA Franc BCEAO",
		symbol: "Fr",
		rateToUSD: 0,
		decimals: 0,
		country: "West African CFA",
		flag: "🇧🇯",
	},
	[CurrencyCode.XPF]: {
		code: CurrencyCode.XPF,
		name: "CFP Franc",
		symbol: "₣",
		rateToUSD: 0,
		decimals: 0,
		country: "CFP Franc Territories",
		flag: "🇵🇫",
	},
	[CurrencyCode.YER]: {
		code: CurrencyCode.YER,
		name: "Yemeni Rial",
		symbol: "﷼",
		rateToUSD: 0,
		decimals: 0,
		country: "Yemen",
		flag: "🇾🇪",
	},
	[CurrencyCode.ZMK]: {
		code: CurrencyCode.ZMK,
		name: "Zambian Kwacha (pre-2013)",
		symbol: "ZK",
		rateToUSD: 0,
		decimals: 2,
		country: "Zambia",
		flag: "🇿🇲",
	},
	[CurrencyCode.ZMW]: {
		code: CurrencyCode.ZMW,
		name: "Zambian Kwacha",
		symbol: "ZK",
		rateToUSD: 0,
		decimals: 2,
		country: "Zambia",
		flag: "🇿🇲",
	},
	[CurrencyCode.ZWL]: {
		code: CurrencyCode.ZWL,
		name: "Zimbabwean Dollar",
		symbol: "$",
		rateToUSD: 0,
		decimals: 2,
		country: "Zimbabwe",
		flag: "🇿🇼",
	},
};

export default currenciesMap;
